# Paths settings
log_file_path: logs/app.logs
group_list: config/group_list.yml
base_dir: /mnt/L-Drive/basic/divg
upload_orders_dir_name: .2BUploaded
data_dir_name: .uploads
failed_uploads_directory_name: .failed_uploads

# Worker settings
max_workers: 4