# General Settings
log_file_path: logs/app.logs

# Main
directory_structure_file_path: config/directory_structure.json

# Data Mover 
landing_dir_base_path: test/test_L_Drive
staging_dir_path: test/test_OMERO_Dir
monitor_interval: 30
stable_duration: 30