# General Settings
log_file_path: logs/app.logs

# Main
directory_structure_file_path: config/directory_structure.json
max_workers: 4

# Data Mover 
landing_dir_base_path: test_mnt/test_L_Drive
staging_dir_path: test_mnt/test_OMERO_Dir
monitor_interval: 30
stable_duration: 30

# Importer
failed_upload_directory: test_mnt/failed_upload_directory